# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b925e00ee344697439114fc5eaeee86205c1fd4fc41693a3eddcac14e49266d9a8be7af84743d2961c3bda60fedd85e021fd4eb5900f48f0720c9f8b4987f776

test:
  secret_key_base: 5c02b89b2dcb4b3c38ec9f98fb9a947598413603f1ed551ca1ed0654310fa965167d4e54ce678db97b1eb09100326fbdceff929904c5168a9686e4a08f1788a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
